version: '2'
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
      - 'cluster.name=docker-cluster'
  elastic-hq:
    image: elastichq/elasticsearch-hq
    ports:
      - 5000:5000
    environment:
      - 'HQ_DEFAULT_URL=http://elastic-search:9200'